config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'pages/about'
  get 'pages/home'
  root "pages#home"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  
  devise_for :professors
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :comissions
  resources :sales
  resources :discounts
  resources :courses
  resources :addresses
  resources :professors
  resources :students

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
    enum status: [:active, :inactive]
    has_one :address
    mount_uploader :photo, PhotoUploader
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        $result == true
        format.html { redirect_to '/', notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :phone, :notes, :status, :email)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(student) do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="body">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.number_field :status %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Notes</th>
      <th>Status</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.phone %></td>
        <td><%= student.notes %></td>
        <td><%= student.status %></td>
        <td><%= student.email %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<!DOCTYPE html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Plataforma de Cursos Online</title>

    <!-- Bootstrap core CSS -->
    <link href="app/assets/stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="app/assets/stylesheets/modern-business.css" rel="stylesheet">

  </head>


<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="/">Plataforma de Cursos Online</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
    </div>
  </div>
</nav>


<h1>Novo estudante</h1>

<div style="width: 500px">
<%= render 'form', student: @student %>
</div>

<%= link_to 'Voltar', "/" %>

<div style="margin-top: 300px">
</div>
<!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Plataforma de Cursos Online 2018</p>
      </div>
      <!-- /.container -->
    </footer>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @student.notes %>
</p>

<p>
  <strong>Status:</strong>
  <%= @student.status %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>