config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'pages/about'
  get 'pages/home'
  root "pages#home"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  
  devise_for :professors
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :comissions
  resources :sales
  resources :discounts
  resources :courses
  resources :addresses
  resources :professors
  resources :students

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
class Professor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    enum kind: [:professor, :system]
    enum status: [:active, :inactive]
    has_many :comissions
    has_many :addresses
    has_many :students
    has_many :courses
    has_many :sales
    mount_uploader :photo, PhotoUploader
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_professor
      @professor = Professor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def professor_params
      params.require(:professor).permit(:name, :email, :role_id, :status, :notes, :balance)
    end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_for(professor) do |f| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :role_id %>
    <%= f.number_field :role_id %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.number_field :status %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="field">
    <%= f.label :balance %>
    <%= f.text_field :balance %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th>Status</th>
      <th>Notes</th>
      <th>Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <td><%= professor.name %></td>
        <td><%= professor.email %></td>
        <td><%= professor.role_id %></td>
        <td><%= professor.status %></td>
        <td><%= professor.notes %></td>
        <td><%= professor.balance %></td>
        <td><%= link_to 'Show', professor %></td>
        <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
        <td><%= link_to 'Destroy', professor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @professor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @professor.email %>
</p>

<p>
  <strong>Role:</strong>
  <%= @professor.role_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @professor.status %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @professor.notes %>
</p>

<p>
  <strong>Balance:</strong>
  <%= @professor.balance %>
</p>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>