config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'pages/about'
  get 'pages/home'
  root "pages#home"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  
  devise_for :professors
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :comissions
  resources :sales
  resources :discounts
  resources :courses
  resources :addresses
  resources :professors
  resources :students

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/discount.rb
class Discount < ApplicationRecord
    enum status: [:active, :inactive]
    enum kind: [:percent, :money]
    has_many :sales
end

app/controllers/discounts_controller.rb
class DiscountsController < ApplicationController
  before_action :set_discount, only: [:show, :edit, :update, :destroy]

  # GET /discounts
  # GET /discounts.json
  def index
    @discounts = Discount.all
  end

  # GET /discounts/1
  # GET /discounts/1.json
  def show
  end

  # GET /discounts/new
  def new
    @discount = Discount.new
  end

  # GET /discounts/1/edit
  def edit
  end

  # POST /discounts
  # POST /discounts.json
  def create
    @discount = Discount.new(discount_params)

    respond_to do |format|
      if @discount.save
        format.html { redirect_to @discount, notice: 'Discount was successfully created.' }
        format.json { render :show, status: :created, location: @discount }
      else
        format.html { render :new }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discounts/1
  # PATCH/PUT /discounts/1.json
  def update
    respond_to do |format|
      if @discount.update(discount_params)
        format.html { redirect_to @discount, notice: 'Discount was successfully updated.' }
        format.json { render :show, status: :ok, location: @discount }
      else
        format.html { render :edit }
        format.json { render json: @discount.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discounts/1
  # DELETE /discounts/1.json
  def destroy
    @discount.destroy
    respond_to do |format|
      format.html { redirect_to discounts_url, notice: 'Discount was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount
      @discount = Discount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_params
      params.require(:discount).permit(:name, :description, :value, :kind, :status)
    end
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/views/discounts/_form.html.erb
<%= form_for(discount) do |f| %>
  <% if discount.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discount.errors.count, "error") %> prohibited this discount from being saved:</h2>

      <ul>
      <% discount.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.number_field :value %>
  </div>

  <div class="field">
    <%= f.label :kind %>
    <%= f.number_field :kind %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.number_field :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/discounts/edit.html.erb
<h1>Editing Discount</h1>

<%= render 'form', discount: @discount %>

<%= link_to 'Show', @discount %> |
<%= link_to 'Back', discounts_path %>

app/views/discounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Discounts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Value</th>
      <th>Kind</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discounts.each do |discount| %>
      <tr>
        <td><%= discount.name %></td>
        <td><%= discount.description %></td>
        <td><%= discount.value %></td>
        <td><%= discount.kind %></td>
        <td><%= discount.status %></td>
        <td><%= link_to 'Show', discount %></td>
        <td><%= link_to 'Edit', edit_discount_path(discount) %></td>
        <td><%= link_to 'Destroy', discount, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Discount', new_discount_path %>

app/views/discounts/new.html.erb
<h1>New Discount</h1>

<%= render 'form', discount: @discount %>

<%= link_to 'Back', discounts_path %>

app/views/discounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @discount.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @discount.description %>
</p>

<p>
  <strong>Value:</strong>
  <%= @discount.value %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @discount.kind %>
</p>

<p>
  <strong>Status:</strong>
  <%= @discount.status %>
</p>

<%= link_to 'Edit', edit_discount_path(@discount) %> |
<%= link_to 'Back', discounts_path %>