config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  get 'pages/about'
  get 'pages/home'
  root "pages#home"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  
  devise_for :professors
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :comissions
  resources :sales
  resources :discounts
  resources :courses
  resources :addresses
  resources :professors
  resources :students

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.role_id == 'system'
        can :manage, :all
      elsif
        can :manage, :all
      end
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :student
  belongs_to :professor
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comission.rb
class Comission < ApplicationRecord
  belongs_to :sale
  belongs_to :professor
  enum status: [:pending, :payd]
end

app/models/course.rb
class Course < ApplicationRecord
    enum status: [:active, :inactive]
    has_many :professor
    mount_uploader :photo, PhotoUploader
end

app/models/discount.rb
class Discount < ApplicationRecord
    enum status: [:active, :inactive]
    enum kind: [:percent, :money]
    has_many :sales
end

app/models/professor.rb
class Professor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    enum kind: [:professor, :system]
    enum status: [:active, :inactive]
    has_many :comissions
    has_many :addresses
    has_many :students
    has_many :courses
    has_many :sales
    mount_uploader :photo, PhotoUploader
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :student
  belongs_to :professor
  belongs_to :discount
  has_many :courses
  has_one :comission

  after_save do
    calc = 0
    self.courses.each {|c| calc += c.price}

    if self.discount
      if self.discount.kind == "percent"
        calc -= calc / self.discount.value
      elsif self.discount.kind == "money"
        calc -= self.discount.value
      end
    end
 
    if self.comission.present?
      self.comission.update(value: (calc * 0.15), status: :pending)
    else
      Comission.create(value: (calc * 0.15), professor: self.professor, sale: self, status: :pending)
    end
  end

end

app/models/student.rb
class Student < ApplicationRecord
    enum status: [:active, :inactive]
    has_one :address
    mount_uploader :photo, PhotoUploader
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :description, :status, :category)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:student_id, :sale_date, :professor_id, :discount_id, :notes)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comissions_helper.rb
module ComissionsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/discounts_helper.rb
module DiscountsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/sales/_form.html.erb
<%= form_for(sale) do |f| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %>
    <%= f.text_field :student_id %>
  </div>

  <div class="field">
    <%= f.label :sale_date %>
    <%= f.date_select :sale_date %>
  </div>

  <div class="field">
    <%= f.label :professor_id %>
    <%= f.text_field :professor_id %>
  </div>

  <div class="field">
    <%= f.label :discount_id %>
    <%= f.text_field :discount_id %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_area :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Sale date</th>
      <th>Professor</th>
      <th>Discount</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.student %></td>
        <td><%= sale.sale_date %></td>
        <td><%= sale.professor %></td>
        <td><%= sale.discount %></td>
        <td><%= sale.notes %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form', sale: @sale %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @sale.student %>
</p>

<p>
  <strong>Sale date:</strong>
  <%= @sale.sale_date %>
</p>

<p>
  <strong>Professor:</strong>
  <%= @sale.professor %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @sale.discount %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @sale.notes %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>